### ISSUE TITLE
Create GitHub Action(s) to process a PR of an NR1 Application

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-catalog#4]
On the initiation of a Pull Request:

- [x] (if possible) Identify the submodule referenced in the PR (assuming one submodule change per PR)
- [x] Checkout / update the submodule
- [x] Build the application
- [x] Lint-check the code
- [x] Validate the structure as an application #3 
- [ ] **N/A - See Comment** ~Lookup a `uuid` in a repo-traceable local data store that maps this submodule to the `global catalog account`. If none exists, generate one and save the `uuid`. If it exists, use that value to perform the next step. See #6.~
- [ ] **N/A - See Comment** ~Validate the ability to publish the code #2~
- [x] Validate the ability to publish the catalog data #1 
- [x] Execute a security and licensing check using Synk

**Comment by jbeveland27** [comment]
These 2 steps are not going to be accomplished on `pull_request`.

**Would need access to commit missing/incorrect uuid to the forked repo for this to work. Instead, this will only be done when PR is approved and merged.**
>- [ ] Lookup a `uuid` in a repo-traceable local data store that maps this submodule to the `global catalog account`. If none exists, generate one and save the `uuid`. If it exists, use that value to perform the next step. See #6.

**There's no secure method for passing needed API keys to a forked repo (#8).**
>- [ ] Validate the ability to publish the code #2

**Comment by jbeveland27** [comment]
The [catalog-pr](https://github.com/newrelic/nr1-catalog/blob/master/.github/workflows/catalog-pr.yml) Workflow now meets these requirements. Closing issue.
