### ISSUE TITLE
Create GitHub Action(s) to merge a PR of an NR1 Application

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-catalog#5]
On merging a Pull Request to `master`, perform the following:

- [x] (if possible) Identify the submodule referenced in the PR (assuming one submodule change per PR)
- [x] Checkout / update the submodule
- [x] Build the application
- [x] ~**Lint** the code~ This was taken care of during PR.
- [x] Lookup a `uuid` in a repo-traceable local data store that maps this submodule to the `global catalog account`. If none exists, generate one and save the `uuid`. If it exists, use that value to perform the next step. See #6 
- [x] Publish the code #2 
- [x] Publish the catalog data #1 
- [ ] (if possible) Notify the appropriate list(s) via Slack of the published change
